apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  interval: 1h
  ref:
    branch: master
  url: https://github.com/prometheus-operator/kube-prometheus
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-setup
  namespace: monitoring
spec:
  healthChecks:
  - kind: Deployment
    name: prometheus-operator
    namespace: monitoring
  interval: 30m
  path: ./manifests/setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  dependsOn:
    - name: kube-prometheus-setup
  healthChecks:
  - kind: StatefulSet
    name: prometheus-k8s
    namespace: monitoring
  - kind: StatefulSet
    name: alertmanager-main
    namespace: monitoring
  - kind: Deployment
    name: grafana
    namespace: monitoring
  - kind: DaemonSet
    name: node-exporter
    namespace: monitoring
  - kind: Deployment
    name: kube-state-metrics
    namespace: monitoring
  - kind: Deployment
    name: prometheus-adapter
    namespace: monitoring
  - kind: Deployment
    name: blackbox-exporter
    namespace: monitoring
  interval: 30m
  path: ./manifests
  patchesStrategicMerge:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: grafana
      namespace: monitoring
    spec:
      template:
        spec:
          containers:
          - name: grafana
            volumeMounts:
            - name: grafana-dashboard-flux-system
              mountPath: /grafana-dashboard-definitions/0/flux-system
              readOnly: false
            - name: grafana-dashboard-qbittorrent
              mountPath: /grafana-dashboard-definitions/0/qbittorrent
              readOnly: false
            - name: grafana-dashboard-longhorn
              mountPath: /grafana-dashboard-definitions/0/longhorn
              readOnly: false
            - name: grafana-cilium-dashboard
              mountPath: /grafana-dashboard-definitions/0/cilium
              readOnly: false
            - name: grafana-cilium-operator-dashboard
              mountPath: /grafana-dashboard-definitions/0/cilium-operator
              readOnly: false
            - name: grafana-hubble-dashboard
              mountPath: /grafana-dashboard-definitions/0/hubble
              readOnly: false
            - name: grafana-dashboard-unifi-controller
              mountPath: /grafana-dashboard-definitions/0/unifi-controller
              readOnly: false
          volumes:
            - configMap:
                name: grafana-dashboard-flux-system
              name: grafana-dashboard-flux-system
            - configMap:
                name: grafana-dashboard-qbittorrent
              name: grafana-dashboard-qbittorrent
            - configMap:
                name: grafana-dashboard-longhorn
              name: grafana-dashboard-longhorn
            - configMap:
                name: grafana-cilium-dashboard
              name: grafana-cilium-dashboard
            - configMap:
                name: grafana-cilium-operator-dashboard
              name: grafana-cilium-operator-dashboard
            - configMap:
                name: grafana-dashboard-unifi-controller
              name: grafana-dashboard-unifi-controller
  - apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    metadata:
      name: k8s
      namespace: monitoring
    spec:
      retentionSize: 5GB
      storage:
        volumeClaimTemplate:
          metadata:
            name: data
          spec:
            resources:
              requests:
                storage: 5Gi
            accessModes:
              - ReadWriteOnce
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-scheduler
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
spec:
  selector:
    component: kube-scheduler
    tier: control-plane
  ports:
  - name: https-metrics
    port: 10259
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-controller-manager
    k8s-app: kube-controller-manager
  name: kube-controller-manager
  namespace: kube-system
spec:
  selector:
    component: kube-controller-manager
    tier: control-plane
  ports:
  - name: https-metrics
    port: 10257
