apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  interval: 30m0s
  ref:
    branch: master
  url: https://github.com/prometheus-operator/kube-prometheus
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-setup
  namespace: monitoring
spec:
  healthChecks:
  - kind: Deployment
    name: prometheus-operator
    namespace: monitoring
  interval: 1h0m0s
  path: ./manifests/setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  timeout: 2m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  dependsOn:
    - name: kube-prometheus-setup
  healthChecks:
  - kind: StatefulSet
    name: prometheus-k8s
    namespace: monitoring
  - kind: StatefulSet
    name: alertmanager-main
    namespace: monitoring
  - kind: Deployment
    name: grafana
    namespace: monitoring
  - kind: DaemonSet
    name: node-exporter
    namespace: monitoring
  - kind: Deployment
    name: kube-state-metrics
    namespace: monitoring
  - kind: Deployment
    name: prometheus-adapter
    namespace: monitoring
  - kind: Deployment
    name: blackbox-exporter
    namespace: monitoring
  interval: 1h0m0s
  path: ./manifests
  patchesStrategicMerge:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: grafana
      namespace: monitoring
    spec:
      template:
        spec:
          containers:
          - name: grafana
            volumeMounts:
            - name: grafana-dashboard-flux-system
              mountPath: /grafana-dashboard-definitions/0/flux-system
              readOnly: false
            - name: grafana-dashboard-qbittorrent
              mountPath: /grafana-dashboard-definitions/0/qbittorrent
              readOnly: false
          volumes:
            - configMap:
                name: grafana-dashboard-flux-system
              name: grafana-dashboard-flux-system
            - configMap:
                name: grafana-dashboard-qbittorrent
              name: grafana-dashboard-qbittorrent
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  timeout: 2m0s
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: addem-se-letsencrypt
    # ingress.kubernetes.io/auth-tls-error-page: getcert.addem.se
    ingress.kubernetes.io/auth-tls-secret: default/client-auth-root-ca-cert
    ingress.kubernetes.io/auth-tls-strict: "true"
    ingress.kubernetes.io/auth-tls-verify-client: "on"
spec:
  tls:
    - hosts:
        - grafana.addem.se
      secretName: grafana-cert
  rules:
    - host: grafana.addem.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-scheduler
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
spec:
  selector:
    component: kube-scheduler
    tier: control-plane
  ports:
  - name: https-metrics
    port: 10259
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-controller-manager
    k8s-app: kube-controller-manager
  name: kube-controller-manager
  namespace: kube-system
spec:
  selector:
    component: kube-controller-manager
    tier: control-plane
  ports:
  - name: https-metrics
    port: 10257
