apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    v1.multus-cni.io/default-network: default/macvlan-conf
    k8s.v1.cni.cncf.io/networks: >
      [{
        "name": "cilium",
        "default-route": []
      }]
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: dougbtv/centos-network
