apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
spec:
  serviceName: qbittorrent
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
        vpn-egress: gateway
    spec:
      securityContext:
        sysctls:
          - name: "net.ipv4.conf.all.src_valid_mark"
            value: "1"
      initContainers:
        - name: wg-quick
          image: nixery.dev/shell/wireguard
          command:
            - wg-quick
            - up
            - /config/wg0.conf
          securityContext:
            privileged: true # not sure which cap is required for sysctl
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
          volumeMounts:
            - name: wg0-conf
              mountPath: /config
        - name: post-up
          image: nixery.dev/shell/wireguard
          command:
            - sh
            - -c
          args:
            - |
              ip route add 10.0.0.0/8 via eth0
              iptables -I OUTPUT -d 10.0.0.0/8 -j ACCEPT
              iptables -A OUTPUT ! -o wg0 -m mark ! --mark $(wg show wg0 fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: wg0-conf
              mountPath: /config
        - name: insert-config
          image: quay.io/quay/busybox
          command: ["sh", "-c"]
          args:
            - |
              OLD="/config/qBittorrent/config/qBittorrent.conf"
              if [ -f $OLD ]; then
                echo "existing config:"
                cat $OLD
                NEW="/config/qBittorrent/config/qBittorrent.$(date "+%s").conf"
                echo "moving existing config to $NEW"
                cp $OLD $NEW
              else
                mkdir -p /config/qBittorrent/config
              fi

              cp /static/qBittorrent.conf $OLD
          volumeMounts:
            - mountPath: /static
              name: static-config
            - mountPath: /config
              name: config
      containers:
        - name: qbittorrent
          image: nixery.dev/qbittorrent-nox
          command: ["qbittorrent-nox", "--profile=/config"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /videos
              name: nfs-videos
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
        - name: srelay
          image: nixery.dev/srelay
          command: ["srelay", "-f"]
          ports:
            - containerPort: 1080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
      volumes:
        - name: wg0-conf
          secret:
            secretName: wg0-conf
            defaultMode: 0600
        - name: static-config
          configMap:
            name: qbittorrent-static-config
        - name: nfs-videos
          nfs:
            path: /export/videos
            server: sergio.localdomain
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        storageClassName: nfs-csi
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
    - name: "http"
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  annotations:
    cert-manager.io/cluster-issuer: addem-se-letsencrypt
    ingress.kubernetes.io/ssl-redirect: "true"
    # ingress.kubernetes.io/auth-tls-error-page: getcert.addem.se
    ingress.kubernetes.io/auth-tls-secret: client-auth-root-ca-cert
    ingress.kubernetes.io/auth-tls-strict: "true"
    ingress.kubernetes.io/auth-tls-verify-client: "on"
spec:
  tls:
    - hosts:
        - qbittorrent.addem.se
      secretName: qbittorrent-cert
  rules:
    - host: qbittorrent.addem.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent
                port:
                  number: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-static-config
data:
  qBittorrent.conf: |
    [LegalNotice]
    Accepted=true

    [Preferences]
    Advanced\RecheckOnCompletion=true
    Downloads\SavePath=/videos/downloads/
    WebUI\AuthSubnetWhitelist=10.0.0.0/8
    WebUI\AuthSubnetWhitelistEnabled=true
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-egress
spec:
  selector:
    vpn-egress: gateway
  ports:
    - name: socks
      port: 1080
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: vpn-egress-gateway
spec:
  endpointSelector:
    matchLabels:
      vpn-egress: gateway
  ingress:
    - fromEntities:
        - cluster
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchName: se1.wg.azirevpn.net
      toPorts:
        - ports:
            - port: "51820"
              protocol: UDP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: vpn-egress-clients
spec:
  endpointSelector:
    matchLabels:
      vpn-egress: client
  ingress:
    - fromEntities:
        - cluster
  egress:
    - toEntities:
        - cluster
    - toEndpoints:
        - matchLabels:
            vpn-egress: gateway
      toPorts:
        - ports:
            - port: "1080"
              protocol: TCP
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wg0-conf
  namespace: default
spec:
  encryptedData:
    wg0.conf: AgCfzMrWKgHhWBhkOX90rmh+pIIrJSx9SgMCu+OAuK7TaCFQr9N4jPLeJGhX4rpoVBTvrLl6ZmGcrMtojlsCW1o+FWEpbeeXCYJB+AVs5TFwztJdZKv4GEJZFkONKpfBcRJBxHd++oJCIHi2PdR11mqLSK687sN+yKqQXRj0969OXQYOAd261bgtlat8ONXbkb1ZSGnHwQiAiIv4beJxXEZG6cLrY0xCfJzr4HGBXL+kxrvPX+3UymDUhDuWDq9Faq/6KKKYBEVhsm6eVozFT2vxvzwyLXoYOLirlhuTj2n/0nKJEAFDEbL0SVB/o7FPZYQRo1wx20KvdCTpTW6XXt8RKhi5LDwN2grLUUfAl22qFT/0b2/aNidzL8BguYJMfZCIGs998AA+2f2vS3qGDiCsODmB0flpRlHE7Zz25QMYoEp0zryqhKIuRdDpT5DSzsq5ZZf2NHit8ke1UF5YSEsYsWaxVwzFuZt17nSQkHqeaHzXDHaXcf5Swt2+RMdu+D5axIzsm5JjPXFRIwafZm7MhEswc8S4TespvDt4Clqf1xnjZj5oze3OcPKzAh5d810FFIkZg5NkIYYau6OICnHgPBsBUAy1qCl3eNkqqWwRtdQCpMfEIDvdLEt4vm0W1jK6LpyZ+Vr30uSy+zb1poO7E+yUQcAaAcGKUDzRjUyQcwqNaZ8yYCYJF3cr9Gq5TKduborlMU3tJArD4SamlBYQ9EdW1/CQgbySx1RMVKHnclogonfNyZqh0h/VC3A2NMD2mJvQ7XF1pJhuDGon2et+i9uycbYxYfasDMr0/SCyu4HnnTsoeKi00q6Wb9bPoLsD64bWfKFbNQ+eSha54MUllZSWEgtFIe2eLUiExp1MRSGqOXKSQ9bNqqYckttCFNwZ+A9/ubPU56//g8p5eikaqQBBtwoJ2A6AFyNJoNJKE6xN+MQDTDsKOenAjDTRzz/KAmg3eoQ4pNA40eJ3/mq75FXM8sk0PbZzbB8JjLSjPSYsUj8eXlOOFriVA+fZmFmIVfUuuVa4tkuo5EnPJyfdbi1ULBTBTbr01tAdG3x8ofEG0gVbcn9UG0NEnuP5rjFzzWduIVhImiuFc+n/eazxDhUQHCOOXkP4JsJQZg46yS8vXXUaukr6ksWM7oBHNM6YGZk/PC2huBvl7tRBvpEryzzPHi/ucv/4fMqOzCNft7nlI8QzcShCs6sLR9eVCYfu3Cz5D/vtwr00mwAJLHO2QXRjhtd+4QovOMI0llaTxfOLtTot6z8IeZwGRJIQU2cytMuUDiXh57fXxgY9tAHqfZdg6/2wMN8CRVbdduIWXp6uG050sOzmPXOzYaQhlYmPZi9e8XdfAqsSX+0fxdpAlJ3fxSRiqD8GgRE6Le96IKSc42T0uQQp4/mkreoO0wT3aLxtkOOImE68wIfCAkNHFCRKmK8Hf10HWltXO/lQYHCK6lIsC9Gdbz6gRMa8aa64xqh0Hea8uc3WABSDjeBtOjGIlTJEuWONo3+SuST8raGJ34vp/d0pffztkJom/vAPQXJhU8RSPOT8pf6UrjzilzChZq0snfAH9qWG8/1R0wcgznqDTjuOfBS3asR8+68jHzrMunO6tQHmMOvZ/8ft0r6eFak5u8wkHrF1IS26Tix8BHnLzKGeK0YE7jVNtKp4vB6mbSMYHBfVCoJqAhKpcmSj2/IFSpEksb7nLW6ODCdJINGQd3lsi5jY5T/1Pt8+st9qL5UT0A==
  template:
    metadata:
      name: wg0-conf
      namespace: default
