apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
spec:
  serviceName: qbittorrent
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
        vpn-egress: client
    spec:
      initContainers:
        - name: insert-config
          image: quay.io/quay/busybox
          command: ["sh", "-c"]
          args:
            - |
              OLD="/config/qBittorrent/config/qBittorrent.conf"
              if [ -f $OLD ]; then
                echo "existing config:"
                cat $OLD
                NEW="/config/qBittorrent/config/qBittorrent.$(date "+%s").conf"
                echo "moving existing config to $NEW"
                cp $OLD $NEW
              else
                mkdir -p /config/qBittorrent/config
              fi

              cp /static/qBittorrent.conf $OLD
          volumeMounts:
            - mountPath: /static
              name: static-config
            - mountPath: /config
              name: config
      containers:
        - name: qbittorrent
          image: nixery.dev/qbittorrent-nox
          command: ["qbittorrent-nox", "--profile=/config"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /videos
              name: nfs-videos
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
      volumes:
        - name: static-config
          configMap:
            name: qbittorrent-static-config
        - name: nfs-videos
          nfs:
            path: /export/videos
            server: sergio.localdomain
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        storageClassName: nfs-csi
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
    - name: "http"
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  annotations:
    cert-manager.io/cluster-issuer: addem-se-letsencrypt
    ingress.kubernetes.io/ssl-redirect: "true"
    # ingress.kubernetes.io/auth-tls-error-page: getcert.addem.se
    ingress.kubernetes.io/auth-tls-secret: client-auth-root-ca-cert
    ingress.kubernetes.io/auth-tls-strict: "true"
    ingress.kubernetes.io/auth-tls-verify-client: "on"
spec:
  tls:
    - hosts:
        - qbittorrent.addem.se
      secretName: qbittorrent-cert
  rules:
    - host: qbittorrent.addem.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent
                port:
                  number: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-static-config
data:
  qBittorrent.conf: |
    [LegalNotice]
    Accepted=true

    [Preferences]
    Connection\Interface=wg0
    Connection\InterfaceName=wg0
    Downloads\SavePath=/videos/downloads/
    WebUI\AuthSubnetWhitelist=10.0.0.0/8
    WebUI\AuthSubnetWhitelistEnabled=true
    WebUI\UseUPnP=false
