apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wg0-conf
  namespace: default
spec:
  encryptedData:
    wg0.conf: AgAcbDx0Vswk2M8fGyoLJZkrlKvDxpu6sm37WHfXaqJMe2nZabGapCFmsD48ZGoDwkEANls+47WkmFO+9rXQC6kLzCFeyBsNU+JHRGMl79b2GokiUgbCQy+G/mvtX3eF/aUof4iPvdEIJkgWYv3GFjM3BDmknR86tPKzi4ENCtLRKtR12EnHtr1JZ39d8b9H/yjgehk1Y+x+pkpScmX1ukV0fEVacZMI6qcTp49FMFC0ATmuWANlH4v0db01HNyKyF3fwNKdgtcQjqk3GF8QRTzGXcocN+vQl2qxy3ignpwN4vQ5B5J3ySQUoVyooWGorusobJ5Ys7vhFkreVnuJXRS2WJ6g2z2wE7Bhd8z4+7HPVtLLk1Pfz72jMAQHUr0HfK2Ymxe7nPg5WPqhsWX0rQfycF0PRnHmdtvAOj4oNT2TDz2I2yvMZW5HLQu1WEjI/STFLZGEc0cnVCFZNXza6msW0o1LAZIC4AS2sI0+bpI+6qPAgfsuCCmQf0Dxrx8rZr6EZQP6XxFr8XAUxVd7iWokbkDee7J15xbHRQZM8H0y1qt8YdymBTTTg2Ft4S6mBLBcf3HvCkn8QwnFFGf3J9QKMCCJ8BtvOXVZBbm6d3/hVHCrOGiqD7BwVKeH8RiZM5a2UyHrbT0PBQtd4RKjZ6osDgQMJbr2oWYdWB4FK3/AnlAwP03GwPTZ4jJyF924bQOSrFJUsKrB11W1/kLjn7xs/4UbVzE/6/k+ksXAb4NZeIxRJ18z8ChQleUV8WR+IEO8lBV4T6UJB/G8+0qhGkpyczuThUlXQJaOzJdBuwrO7jIo0qqToIZ7EDIpwazklMHK7IfuKV+vwcNkU2XlQVBH8V6bjFp8vGCeNThrnmgB3ih0aWVqLgJGMAXK1hX+m1W9LjDp/NoB5geiH0WGDsmypaAITkcCmCtvoLx9wBwmNWdnKct3VLrYPNV+O+q6YWFUiY+BpIdMvgWaide6KdEk99y/oQpSk5JFvUPeSBTMv4MQY/RWdhf6l0VGCxk/EvoWdN/2L47bHprqw/Zw/pEcNqPdt52kIUA+HfPNmjgpXMhflhsi6Plmv6cpo5E2RRgkesDKT7o=
  template:
    metadata:
      name: wg0-conf
      namespace: default
