apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: unifi-controller
  name: unifi-controller
spec:
  replicas: 1
  serviceName: unifi-controller
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
      labels:
        app: unifi-controller
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: copy-static
          image: quay.io/quay/busybox
          command:
            - cp
            - -r
            - --no-target-directory
            - /static
            - /
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-data-sites-default
              mountPath: /static/config/data/sites/default
      containers:
        - image: ghcr.io/linuxserver/unifi-controller:version-6.0.45
          name: unifi-controller
          env:
            - name: MEM_LIMIT
              value: 1024M
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          ports:
            - containerPort: 8443
          volumeMounts:
            - mountPath: /config
              name: config
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: config-data-sites-default
          configMap:
            name: config-data-sites-default
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
