apiVersion: v1
kind: Service
metadata:
  name: unifi-controller
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
spec:
  ports:
    - name: https
      port: 8443
  selector:
    app: unifi-controller
