apiVersion: v1
kind: Service
metadata:
  labels:
    app: unifi-controller
  name: unifi-controller
spec:
  ports:
    - name: https
      port: 8443
    - name: metrics
      port: 9130
  selector:
    app: unifi-controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unifi-controller
spec:
  selector:
    matchLabels:
      app: unifi-controller
  endpoints:
  - interval: 60s
    port: metrics
