apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: droppy
spec:
  serviceName: droppy
  selector:
    matchLabels:
      app: droppy
  template:
    metadata:
      labels:
        app: droppy
    spec:
      containers:
        - name: web
          image: ghcr.io/addreas/droppy:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DATA_DIR
              value: /data
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
          volumeMounts:
            - mountPath: /data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-csi"
        resources:
          requests:
            storage: 1G
---
apiVersion: v1
kind: Service
metadata:
  name: droppy
spec:
  selector:
    app: droppy
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: droppy
  annotations:
    cert-manager.io/cluster-issuer: addem-se-letsencrypt
spec:
  tls:
    - hosts:
        - drop.addem.se
      secretName: droppy-cert
  rules:
    - host: drop.addem.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: droppy
                port:
                  number: 8080
