apiVersion: v1
kind: Service
metadata:
  name: hass2
  labels:
    app: hass
spec:
  ports:
    - name: http
      port: 8123
  selector:
    app: hass
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hass
spec:
  endpoints:
  - port: "http"
    interval: 60s
    path: "/api/prometheus"
  selector:
    matchLabels:
      app: hass
