apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: haproxy
  namespace: kube-system
spec:
  interval: 1m
  url: https://haproxytech.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kubernetes-ingress
      version: v1.4.4
      sourceRef:
        kind: HelmRepository
        name: haproxy
        namespace: kube-system
      interval: 1m
