apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.1.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 1m
  values:
    installCRDs: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: addem-se-letsencrypt
spec:
  acme:
    email: andreas+acme@addem.se
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: addem-se-letsencrypt-private-key
    solvers:
      - dns01:
          cloudflare:
            email: addem1234@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAQ+E0+KOtrhC//Xu2NjZN6Q1qCm4Q7uMa+THYn/2q54SBsqCx3/C5HJ2sCctLLPEGPQdUDaNMhqu5ee3/4f4glkSUKZEmmVIFeMVIxIGCKEwZnRkbDdzstxaUUALQJtD3PfbHzSndGrM9fozvvG0GKFTbflYAKqaReZu/vCm84Igkj+scjJ5JAi8dQbEiwCdm+W4x1/upxCm6+GdkzSciY5wAZZGzD6x17NlTmaVvtIq1SkWpnF6AWxeGoSSMJbTy2KD/c/8ou51/N/P/IGVxUXQxzRIC9OoLBTIw72nca7kLShItTSzIQVlATEH0YJ1DVK6N2hHL9laDQf1uzMmwSkaJ+PrxCwu8wyTWBExqFey1k7SxXQfR/SXaWIahOYJQUvJ6ZaK/dMEdglyBvrEc3YEzzrembLgvIp/L4Fxyg/05w5UW5CU8HxoI5gZ1nmCOcPjJMnhkCBadfrmqA/AedSoO80c+L66qwN1UAoxQI2VQXD6yQmPRthkWgWJkxEyDtX3sYvySDFUkZgg6so0N48uyMv3KBTKkkWTOFDl29BZF4KiMKEH4VVOToJXrH6NCzGo36GfYNjuRFHtub6b5iVNMXxNSiZnyBbJ+QsVq0T6fHwRqinFpNVzTootMJH9yqsL8ga/M95ZvBrWf6fA5muWyvthZzW+9NuU2uM9eHQHAczgxZVC/QkPDmwf3/kH56EI7AvZy1X/TwqKZeZKzjzpkZwM2J8zgvC+FJkzXsI5OUbd0T16uz
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
