apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: v1.9.4
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 1h
  values:
    prometheus:
      enabled: true
    operator:
      prometheus:
        enabled: true
    hubble:
      metrics:
        enabled: true

# perhaps?
# https://archive.fosdem.org/2020/schedule/event/containers_bpf/
# https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/
