apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: haproxy-ingress
  namespace: kube-system
spec:
  interval: 1m
  url: https://haproxy-ingress.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: haproxy-ingress
      version: 0.12.0-beta.2
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: kube-system
      interval: 1m
---
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: unauthenticated
spec:
  controller: haproxy-ingress.github.io/controller
  parameters:
    kind: ConfigMap
    name: certificate-authenticated-ingress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certificate-authenticated-ingress
  namespace: kube-system
data:
  ssl-redirect: "true"
---
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: certificate-authenticated
spec:
  controller: haproxy-ingress.github.io/controller
  parameters:
    kind: ConfigMap
    name: certificate-authenticated-ingress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certificate-authenticated-ingress
  namespace: kube-system
data:
  ssl-redirect: "true"
  # auth-tls-error-page: https://getcert.addem.se
  auth-tls-secret: default/client-auth-root-ca-cert
  auth-tls-strict: "true"
  auth-tls-verify-client: "on"
