apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: haproxytech
  namespace: kube-system
spec:
  interval: 1m
  url: https://haproxytech.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kubernetes-ingress
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: haproxytech
        namespace: kube-system
      interval: 1m
  values:
    controller:
      replicaCount: 1
      unprivileged: true
      service:
        type: LoadBalancer
