apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: haproxy-ingress
  namespace: kube-system
spec:
  interval: 1h
  url: https://haproxy-ingress.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: haproxy-ingress
      version: 0.12.0-beta.2
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: kube-system
      interval: 1h
  values:
    controller:
      replicaCount: 2
      # stats:
      #   enabled: true
      # metrics:
      #   enabled: true
      # serviceMonitor:
      #   enabled: true
      extraArgs:
        watch-ingress-without-class: "true"
        allow-cross-namespace: "true"
