apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nfs-csi
  namespace: kube-system
spec:
  interval: 1m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-csi
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-nfs
      version: v2.0.0
      sourceRef:
        kind: HelmRepository
        name: nfs-csi
        namespace: kube-system
      interval: 1m
  values:
    image:
      nfs:
        tag: canary
      csiProvisioner:
        tag: v1.6.0
    controller:
      replicas: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: sergio.localdomain
  share: /export/nfs-csi
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
