apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: smb-csi
  namespace: kube-system
spec:
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  chart: csi-driver-smb
  version: v0.6.0
  set:
    controller.replicas: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-csi
provisioner: smb.csi.k8s.io
parameters:
  csi.storage.k8s.io/node-stage-secret-name: "sergio-smb-credentials"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
  source: "//sergio.localdomain/smb-csi"
  createSubDir: "true"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
