{
 "title": "Periserve",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{namespace=\"periserve\"}[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request rate by status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(sum(http_requests_total{namespace=\"periserve\"}) by (status_code)[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Latency histogram",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(sum(http_request_duration_seconds_bucket{namespace=\"periserve\"}) by(le)[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Visited paths",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sort_desc(sum(http_requests_total{namespace=\"periserve\", path!~\".*js$\"}) by (path))"
    }
   ]
  }
 ]
}