apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: urly-redis
spec:
  serviceName: urly-redis
  selector:
    matchLabels:
      app: urly-redis
  template:
    metadata:
      labels:
        app: urly-redis
    spec:
      containers:
        - name: redis
          image: "redis:alpine"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-csi"
        resources:
          requests:
            storage: 1G
---
apiVersion: v1
kind: Service
metadata:
  name: urly-redis
spec:
  selector:
    app: urly-redis
  ports:
    - name: "redis"
      port: 6379
      targetPort: 6379
