# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/007e8a33-0f88-4755-9150-afd2aff1d4e7";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/586E-6973";
      fsType = "vfat";
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/007e8a33-0f88-4755-9150-afd2aff1d4e7";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/007e8a33-0f88-4755-9150-afd2aff1d4e7";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/lib" =
    {
      device = "/dev/disk/by-uuid/007e8a33-0f88-4755-9150-afd2aff1d4e7";
      fsType = "btrfs";
      options = [ "subvol=@varlib" ];
    };

  fileSystems."/var/log" =
    {
      device = "/dev/disk/by-uuid/007e8a33-0f88-4755-9150-afd2aff1d4e7";
      fsType = "btrfs";
      options = [ "subvol=@varlog" ];
    };

  fileSystems."/var/lib/longhorn" =
    {
      device = "/dev/disk/by-uuid/0a40c243-115c-4bf2-bbab-182233de5e80";
      fsType = "ext4";
    };

  fileSystems."/var/lib/longhorn2" =
    {
      device = "/dev/disk/by-uuid/957d2327-04ac-403e-9f35-1a4610342f7d";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u3u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
