apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gotk-monitor
  namespace: flux-system
spec:
  podMetricsEndpoints:
    - port: http-prom
      interval: 30s
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - source-controller
          - kustomize-controller
          - helm-controller
          - notification-controller
