apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: nucles.localdomain:6443
    token: "" # from kubeadm-init.yaml or `kubeadm token create`
    unsafeSkipCAVerification: true
controlPlane:
  certificateKey: "" # from kubeadm-init.yaml or `kubeadm init phase upload-certs --upload-certs`

#kubeadm join nucles.localdomain:6443 --config kubeadm-join.yaml
#kubectl taint nodes --all node-role.kubernetes.io/master-
