apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
certificateKey: "" # kubeadm certs certificate-key
bootstrapTokens:
- groups:
  -  system:bootstrappers:kubeadm:default-node-token
  token: "" # kubeadm token generate
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: nucles
apiServer:
  certSANs:
  - nucles.localdomain
  - sergio.localdomain
  - nucle1.localdomain
  - nucle2.localdomain
controlPlaneEndpoint: nucles.localdomain:6443
controllerManager:
  extraArgs:
    bind-address: 0.0.0.0
scheduler:
  extraArgs:
    bind-address: 0.0.0.0
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
allowedUnsafeSysctls:
  - net.ipv4.conf.all.src_valid_mark

#kubeadm init --upload-certs --config kubeadm-init.yaml
#kubectl taint nodes --all node-role.kubernetes.io/master-
