apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook-ceph-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./bases/rook-ceph/operator
  targetNamespace: rook-ceph
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  patchesStrategicMerge:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rook-ceph-operator
    spec:
      template:
        spec:
          containers:
          - name: rook-ceph-operator
            env:
            - name: ROOK_ENABLE_DISCOVERY_DAEMON
              value: "true"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: rook-ceph-operator
  path: ./bases/rook-ceph/cluster
  targetNamespace: rook-ceph
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
