apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook-ceph-setup
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./bases/rook-ceph/setup
  targetNamespace: rook-ceph
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: rook-ceph-setup
  path: ./bases/rook-ceph/cluster
  targetNamespace: rook-ceph
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
