name: Homelab Dependency Check
"on":
  schedule:
    - cron: 30 14 * * 6
jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Install `cue`, `jsonnet`, `jb`, `jq`
        run: |-
          go install cuelang.org/go/cmd/cue@v0.4.3
          go install github.com/google/go-jsonnet/cmd/jsonnet@latest
          go install github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest

          JQ=/usr/bin/jq
          sudo curl -sLo $JQ https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          sudo chmod +x $JQ
      - run: cue cmd -t githubToken=${{ secrets.GITHUB_TOKEN }} update-github-tags
      - run: cue cmd update-jsonnet-defs
      - run: cue cmd update-gomod-defs
      - run: cue cmd update-gomod-tags
      - run: git diff
      - run: cue vet -c ./resources/...
      - name: Create Pull Request
        with:
          title: Updated dependencies
          body: Automatically updated dependencies. The changes have passed a `cue vet -c ./resources/...`.
          commit-message: Automatically update dependencies/definitions
          branch: automatically-update-deps
        uses: peter-evans/create-pull-request@v4
