name: Homelab Dependency Check
"on": [workflow_dispatch]
jobs:
  update-go-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup CUE environment
        uses: cue-lang/setup-cue@v1.0.0-alpha.2
      - name: Install JQ
        run: |
          JQ=/usr/bin/jq
          curl -sLo $JQ https://stedolan.github.io/jq/download/linux64/jq
          
      - run: cue cmd update-gomod-defs
      - run: cue cmd update-gomod-tags
      - run: cue vet -c ./resources/...
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Automatically update go dependencies/definitions
#  update-jsonnet-deps:
#    runs-on: ubuntu-latest
#    container: nixery.dev/shell/cue/jq/git
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v3
#      - run: cue cmd update-jsonnet-defs
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v4
#        with:
#          commit-message: Automatically update jsonnet dependencies/definitions
#  update-github-release-tags:
#    runs-on: ubuntu-latest
#    container: nixery.dev/shell/cue/jq/git
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v3
#      - run: cue cmd update-github-tags
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v4
#        with:
#          commit-message: Automatically update github release tags
