name: longhorn-images

on:
  push:
    branches:
      - 'main'
    # paths:
      # - 'tags.cue'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: cue-lang/setup-cue@v1.0.0
      - run: | 
         echo LONGHORN_VERSION=$(cue export --out yaml -e 'githubReleases["longhorn/longhorn"]') >> $GITHUB_ENV

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/longhorn-manager:${{ env.LONGHORN_VERSION }}
          build-args: |
            VERSION=${{ env.LONGHORN_VERSION }}
          context: ./resources/system/longhorn-system
          file: ./resources/system/longhorn-system/longhorn-manager.Dockerfile
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/longhorn-instance-manager:${{ env.LONGHORN_VERSION }}
          build-args: |
            VERSION=${{ env.LONGHORN_VERSION }}
          context: ./resources/system/longhorn-system
          file: ./resources/system/longhorn-system/instance-manager.Dockerfile
